// <auto-generated />
namespace FarmerPro.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addchatcart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addchatcart));
        
        string IMigrationMetadata.Id
        {
            get { return "202402010722128_add chat cart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
