// <auto-generated />
namespace FarmerPro.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class inituser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inituser));
        
        string IMigrationMetadata.Id
        {
            get { return "202401310414268_init user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
